name        = "HyperTexte 1DFH"
name8       = "hyper1dk"
locale      = "fr"
variant     = "1DK"
description = "Disposition HyperTexte, pour une saisie plus rapide de texte."
author      = "Adrien MOYAUX"
url         = "https://hypertexte.beseven.fr"
geometry    = "ERGO"
version     = "1.1.2"

base = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆ +   ┃ 1   │ 2   │ 3   │ 4   │ 5   ┃ 6   │ 7   │ 8   │ 9   │ º   ┃ €   ┆ %   ┆
┆ =   ┃     │     │     │     │     ┃     │     │     │     │ 0 ° ┃ €   ┆ %   ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ Z   │ Y   │ O   │ W   │ B   ┃ F   │ D   │ L   │ P   │ ?   ┃ {   ┆ }   ┆
·     ┃   á │   í │     │     │     ┃     │     │   û │   q │ ’ ? ┃ [   ┆ ]   ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ A   │ I   │ E   │ U   │ K   ┃ V   │ S   │ N   │ T   │ R   ┃ "   ┆ |   ┆
·     ┃   è │   é │   œ │     │     ┃     │     │   ô │     │     ┃ '   ┆ \   ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆ Ê   ┃ :   │ J   │ À   │*¨   │ ;   ┃ M   │ C   │ H   │ G   │ X   ┃           ·
┆   ^ ┃ . ù │   æ │   ê │***¨ │ ,   ┃   ñ │   ç │   î │     │   â ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

altgr = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃   ¹ │   ² │   ³ │   ⁴ │   ⁵ ┃   ⁶ │   ⁷ │   ⁸ │   ⁹ │   ⁰ ┃     ┆     ┆
┆     ┃   ₁ │   ₂ │   ₃ │   ₄ │   ₅ ┃   ₆ │   ₇ │   ₈ │   ₉ │   ₀ ┃     ┆     ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃   „ │   „ │     │     │   “ ┃   ” │   § │   ≠ │   ± │   ¿ ┃     ┆     ┆
·     ┃   ` │   @ │   % │   ! │   « ┃   » │   $ │   = │   + │   ' ┃     ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃   ≤ │   ≥ │     │     │     ┃   ¦ │   — │   – │     │     ┃     ┆     ┆
·     ┃   < │   > │   { │   } │   \ ┃   | │   ( │   ) │   [ │   ] ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆     ┃   … │     │     │     │   · ┃   − │   € │   £ │   ≈ │   × ┃           ·
┆     ┃   : │   / │   = │   " │   ; ┃   & │   ^ │   # │   ~ │   * ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

[spacebar]
shift       = "-"
altgr       = "_"
altgr_shift = "\u00a0"  # NO-BREAK SPACE
1dk         = "\u00a0"  # NO-BREAK SPACE
1dk_shift   = "\u202f"  # NARROW NO-BREAK SPACE
